### ISSUE TITLE
migrate to GA? 

### ISSUE THREAD

**Issue by dannygoldstein** [cesium-ml/baselayer#190]
The CI currently still uses travis-ci, which lately has been having super long queue times -- e.g., ~30 minutes on https://travis-ci.org/github/cesium-ml/baselayer/builds/755471873. Given these performance issues and the fact that travis-ci.org is going away, perhaps we should consider migrating to github actions.

**Comment by stefanv** [comment]
:+1: That makes sense.

**Comment by dmitryduev** [comment]
Migrated, closing.
