### ISSUE TITLE
Dedicated Web Workers for API-only calls

### ISSUE THREAD

**Issue by profjsb** [cesium-ml/baselayer#209]
Rather than have bulk/programmatic API calls bog down and block the frontend user experience, baselayer should allow for a separate pool of webworkers to handle API-only calls. This will not fully solve the need for autoscaling under large loads (which is complicated by webtokens) but it will go a long way.

**Comment by acrellin** [comment]
nginx can detect whether a request comes from a browser or not, so it should be fairly straightforward to direct requests accordingly

**Comment by acrellin** [comment]
Implemented
