### ISSUE TITLE
pre-commit install fails

### ISSUE THREAD

**Issue by mcoughlin** [cesium-ml/baselayer#301]
https://github.com/cesium-ml/baselayer/runs/6087746770?check_suite_focus=true

@stefanv 

usage: pre-commit run [-h] [--color {auto,always,never}] [-c CONFIG]
                      [--verbose] [--all-files | --files [FILES [FILES ...]]]
                      [--show-diff-on-failure]
                      [--hook-stage {commit,merge-commit,prepare-commit-msg,commit-msg,post-commit,manual,post-checkout,push,post-merge,post-rewrite}]
                      [--remote-branch REMOTE_BRANCH]
                      [--local-branch LOCAL_BRANCH] [--from-ref FROM_REF]
                      [--to-ref TO_REF]
                      [--commit-msg-filename COMMIT_MSG_FILENAME]
                      [--remote-name REMOTE_NAME] [--remote-url REMOTE_URL]
                      [--checkout-type CHECKOUT_TYPE]
                      [--is-squash-merge IS_SQUASH_MERGE]
                      [--rewrite-command REWRITE_COMMAND]
                      [hook]
pre-commit run: error: argument --from-ref/--source/-s: expected one argument

**Comment by stefanv** [comment]
Thanks, I pushed a fix.
