### ISSUE TITLE
Ensure pinned version of baselayer gets checked out

### ISSUE THREAD

**Issue by acrellin** [cesium-ml/baselayer#39]
Currently latest master commit gets checked out

**Comment by stefanv** [comment]
I think the tool currently does what it was designed to do: check out the version specified in `.gitmodules`:

$ cat .gitmodules 
[submodule "baselayer"]
	path = baselayer
	url = https://github.com/cesium-ml/baselayer.git
	branch = master

**Comment by acrellin** [comment]
no commit is specified here, though

**Comment by stefanv** [comment]
Exactly.  If we wanted a specific commit, that's closer to git default behavior.  So we can then get rid of the update script.  I think we had it there to make sure we're always in sync with the latest baselayer which, now that baselayer has stabilized, seems less desirable.

@bnaul Do you remember anything about our rationale here?

**Comment by bnaul** [comment]
I think I just avoided using this script altogether bc I was never sure what it would do 😬. Always just manually updated the submodule as needed...

**Comment by stefanv** [comment]
That reinforces my feeling that this used to solve a problem that no longer exists.  We should get rid of the script, and restore it if we see a need (and then document why ;).
